In [7]:
import pandas as pd

# 读取数据
df=pd.DataFrame({
   'student_id':[1,2,3,4,5],
    'score':[90,185,88,92,-87]
})

#计算均值和标准差
mean=df['score'].mean()
std=df['score'].std()

#计算每个数据点的z-score
df['z_score']=abs(df['score']-mean)/std

#检测异常值
outliers=df[df['z_score']>1]

outliers

   student_id  score   z_score
1           2    185  1.127943
4           5    -87  1.626101

In [8]:
import pandas as pd

#创建示例数据
student_data=pd.DataFrame({
    'student_id':[1,2,3,4,5,4],
    'score':[90,85,88,92,87,92]
})

#删除重复值
unique_student_data=student_data.drop_duplicates()

unique_student_data

   student_id  score
0           1     90
1           2     85
2           3     88
3           4     92
4           5     87

In [6]:
import pandas as pd

file_path='24年C题/附件1.xlsx'

df=pd.read_excel(file_path)

df

   地块名称   地块类型  地块面积/亩                                                说明
0    A1    平旱地    80.0  (1) 平旱地、梯田和山坡地每年都只能种植一季作物。\n\n(2) 水浇地每年可以种植一季也...
1    A2    平旱地    55.0                                                NaN
2    A3    平旱地    35.0                                                NaN
3    A4    平旱地    72.0                                                NaN
4    A5    平旱地    68.0                                                NaN
5    A6    平旱地    55.0                                                NaN
6    B1     梯田    60.0                                                NaN
7    B2     梯田    46.0                                                NaN
8    B3     梯田    40.0                                                NaN
9    B4     梯田    28.0                                                NaN
10   B5     梯田    25.0                                                NaN
11   B6     梯田    86.0                                                NaN
12   B7     梯田    55.0                                                NaN
13   B8     梯田    44.0                                                NaN
14   B9     梯田    50.0                                                NaN
15  B10     梯田    25.0                                                NaN
16  B11     梯田    60.0                                                NaN
17  B12     梯田    45.0                                                NaN
18  B13     梯田    35.0                                                NaN
19  B14     梯田    20.0                                                NaN
20   C1    山坡地    15.0                                                NaN
21   C2    山坡地    13.0                                                NaN
22   C3    山坡地    15.0                                                NaN
23   C4    山坡地    18.0                                                NaN
24   C5    山坡地    27.0                                                NaN
25   C6    山坡地    20.0                                                NaN
26   D1    水浇地    15.0                                                NaN
27   D2    水浇地    10.0                                                NaN
28   D3    水浇地    14.0                                                NaN
29   D4    水浇地     6.0                                                NaN
30   D5    水浇地    10.0                                                NaN
31   D6    水浇地    12.0                                                NaN
32   D7    水浇地    22.0                                                NaN
33   D8    水浇地    20.0                                                NaN
34   E1  普通大棚      0.6                                                NaN
35   E2  普通大棚      0.6                                                NaN
36   E3  普通大棚      0.6                                                NaN
37   E4  普通大棚      0.6                                                NaN
38   E5  普通大棚      0.6                                                NaN
39   E6  普通大棚      0.6                                                NaN
40   E7  普通大棚      0.6                                                NaN
41   E8  普通大棚      0.6                                                NaN
42   E9  普通大棚      0.6                                                NaN
43  E10  普通大棚      0.6                                                NaN
44  E11  普通大棚      0.6                                                NaN
45  E12  普通大棚      0.6                                                NaN
46  E13  普通大棚      0.6                                                NaN
47  E14  普通大棚      0.6                                                NaN
48  E15  普通大棚      0.6                                                NaN
49  E16  普通大棚      0.6                                                NaN
50   F1   智慧大棚     0.6                                                NaN
51   F2   智慧大棚     0.6                                                NaN
52   F3   智慧大棚     0.6                                                NaN
53   F4   智慧大棚     0.6                                                NaN

In [11]:
import pandas as pd

file_path="23年C题/附件2.xlsx"

df=pd.read_excel(file_path)

df

,销售日期,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售
0,2020-07-01,09:15:07.924,102900005117056,0.396,7.6,销售,否
1,2020-07-01,09:17:27.295,102900005115960,0.849,3.2,销售,否
2,2020-07-01,09:17:33.905,102900005117056,0.409,7.6,销售,否
3,2020-07-01,09:19:45.450,102900005115823,0.421,10.0,销售,否
4,2020-07-01,09:20:23.686,102900005115908,0.539,8.0,销售,否
...,...,...,...,...,...,...,...
878498,2023-06-30,21:35:13.264,102900005115250,0.284,24.0,销售,否
878499,2023-06-30,21:35:14.358,102900011022764,0.669,12.0,销售,否
878500,2023-06-30,21:35:20.264,102900005115250,0.125,24.0,销售,否
878501,2023-06-30,21:35:21.509,102900011016701,0.252,5.2,销售,否
878502,2023-06-30,21:40:48.248,102900011022764,0.803,12.0,销售,否

In [16]:
import pandas as pd

file_path="24年C题/附件2.xlsx"

df=pd.read_excel(file_path,sheet_name="2023年统计的相关数据")

df_cleaned= df.dropna()

df_cleaned

      序号 作物编号 作物名称  地块类型 种植季次    亩产量/斤  种植成本/(元/亩)  销售单价/(元/斤)
0      1    1   黄豆   平旱地   单季    400.0       400.0   2.50-4.00
1      2    2   黑豆   平旱地   单季    500.0       400.0   6.50-8.50
2      3    3   红豆   平旱地   单季    400.0       350.0   7.50-9.00
3      4    4   绿豆   平旱地   单季    350.0       350.0   6.00-8.00
4      5    5   爬豆   平旱地   单季    415.0       350.0   6.00-7.50
..   ...  ...  ...   ...  ...      ...         ...         ...
102  103   30  生菜   智慧大棚  第二季   4500.0      2200.0   5.40-7.20
103  104   31   辣椒  智慧大棚  第二季   1800.0      1300.0  7.20-10.20
104  105   32  空心菜  智慧大棚  第二季  11000.0      5500.0   3.60-7.20
105  106   33  黄心菜  智慧大棚  第二季   5400.0      2750.0   4.80-6.00
106  107   34   芹菜  智慧大棚  第二季   6000.0      1200.0   3.80-5.80

[107 rows x 8 columns]